admin:
    pattern:   /admin/
    defaults:  { _controller: AcmeCatalogBundle:Default:admin } 


AcmeCatalogBundle:
    resource: "@AcmeCatalogBundle/Controller/"
    type: annotation
    prefix: /
    
login:
    pattern:   /login
    defaults:  { _controller: AcmeCatalogBundle:Security:login }
    
login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
    defaults:  { _controller: AcmeCatalogBundle:Security:logout }

registration:
    pattern:   /registration
    defaults:  { _controller: AcmeCatalogBundle:Security:registration }  

testform:
    pattern:   /testform
    defaults:  { _controller: AcmeCatalogBundle:Security:testform } 
   
test_testform:
    pattern:   /test_testform
    defaults:  { _controller: AcmeCatalogBundle:Security:testform } 
    
new:
    pattern:   /new
    defaults:  { _controller: AcmeCatalogBundle:Security:new }
    
task_new:
    pattern:   /task_new
    defaults:  { _controller: AcmeCatalogBundle:Security:new }

createuser:
    pattern:   /createuser
    defaults:  { _controller: AcmeCatalogBundle:Security:createuser }
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
