_default:
    pattern:  /
    defaults: { _controller: AcmeCatalogBundle:Default:index }

AcmeCatalogBundle:
    resource: "@AcmeCatalogBundle/Controller/"
    type:     annotation
    prefix:   /
    
testcatalog:
    pattern:   /testcatalog
    defaults:  { _controller: AcmeCatalogBundle:Default:index }


login:
    pattern:   /login
    defaults:  { _controller: AcmeCatalogBundle:Security:login }
    
login_check:
    pattern:   /login_check



    
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
